openapi: 3.0.0
info:
  title: Learn express and swagger -LearnCodeOnline
  description: LCO - a Code segment to writing code.
  version: 1.1.0
  contact: 
    email: manohar@goggle.com
    url: "https://lco.dev"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for local host
#   - url: "http://localhost:4000/api/v1"
#     description: for local host

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default:
          - v1
      protocol:
        enum:
          - http
          - https
        default:
          - http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BasicAuth:
      type: http
      scheme: basic

paths:
  /lco:
    get:
      tags:
        - String
      summary: returns a greet message from LCO
      responses:
        200:
          description: Success Message from LCO
          content:
            application/json:
              schema:
                type: string
                example: "MyString"
        400:
          description: Bad Request
        500:
          description: Internal Server Error
    
  /lcoObject:
    get:
      tags:
        - Object
      summary: returns an unique object
      responses:
        200:
          description: Success Message from LCO Object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  course:
                    type: string
                  price:
                    type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error
  
  /lcoArray:
    get:
      tags:
        - Array
      summary: returns an all courses
      responses:
        200:
          description: Success Message from LCO Courses
          content:
            application/json:
              schema:
                type: array
                  items: object
                properties:
                  id:
                    type: string
                  course:
                    type: string
                  price:
                    type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error
    
  /myCourses/{courseId}:
    get:
      tags:
        - String
      summary: returns a course based on courseId
      parameters:
        - name: courseId
          in: path
          required: true
          default: 22
          schema:
            type: string
      responses:
        200:
          description: Success Message from LCO Courses
          content:
            application/json:
              schema:
                type: object
              properties:
                id:
                  type: string
                course:
                  type: string
                price:
                  type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error
  
  /addCourses: 
    post:
      tags:
        - String
      summary: Add the courses
      consumes:
        -application/json
      produces:
        -application/json
      requestBody:
        required: true;
        content:
          application/json:
            schema:
              type: object
            properties:
              id:
                type: string
                  course:
                type: string
                price:
                  type: number
      responses:
        200:
          description: Success Message from LCO Courses
          content:
            application/json:
              schema:
                type: object
              properties:
                id:
                  type: string
                course:
                  type: string
                price:
                  type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error

  /courseQuery: 
    get:
      tags:
        - String
      summary: Query Selector
      parameters:
        - name: location
          in: query
          schema:
            type: String
            enum: [banglore, kerala, jaipur]
        - name: device
          in: query
          schema:
            type: String
            enum: [web, mobile]
      responses:
        200:
          description: All good
          content:
            application/json:
              schema:
                type: object
              properties:
                location:
                  type: string
                devices:
                  type: string
        400:
          description: Bad Request
        500:
          description: Internal Server Error